name: flutter_rentalmotor
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  fl_chart: ^0.69.2
  web_socket_channel: ^2.4.0
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.1.0
  animated_text_kit: ^4.2.3
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.1.2
  flutter_typeahead: ^5.2.0

  font_awesome_flutter: ^10.4.0
  intl: 0.19.0
  lottie: ^3.2.0
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.2
  image_picker: ^0.8.5+3
  flutter_keyboard_visibility: ^6.0.0
  pointer_interceptor: ^0.10.1+2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  badges: ^3.1.2
  another_flushbar: ^1.10.29
  permission_handler: ^11.3.1
  rename: ^3.0.2
  flutter_launcher_icons: ^0.14.3
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons: # Ganti ini dari flutter_launcher_icons
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo1.png
    - assets/images/logo.png
    - assets/images/chat.png
    - assets/images/m1.png
    - assets/images/m2.png
    - assets/images/m3.png
    - assets/images/m4.png
    - assets/images/m5.png
    - assets/images/m6.png
    - assets/images/m7.png
    - assets/images/m8.png
    - assets/images/m9.png
    - assets/images/m10.png
    - assets/images/m11.png
    - assets/images/animations/welcome.json
    - assets/images/c1.png
    - assets/images/c2.png
    - assets/images/default_motor.png
